language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - set -e
    - composer build

deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file: build/aws-excfwd
    skip_cleanup: true
    on:
      tags: true
      php: '7.1'